import type { WorkGame } from "../game/workGames";

/** Card titles per kind of work. The mini-game is how the ticket gets done. */
export const TICKET_TITLES: Record<WorkGame, readonly string[]> = {
  tidy: [
    "Checkout button sits off-center on mobile",
    "Settings page spacing drifted after the redesign",
    "Empty state shows the wrong illustration",
    "Header overlaps the menu on small screens",
    "Profile card uses last year's colors",
    "Onboarding step 3 doesn't match the mockup",
    "Dark mode leaves one panel bright white",
    "Pricing table columns are out of line",
    "Toast messages cover the save button",
    "Login form fields are different widths",
  ],
  spot: [
    "QA found a regression in search results",
    "Customer says the total is wrong at checkout",
    "Screenshot diff failed on the dashboard",
    "Something changed on the invoice page",
    "Support ticket: avatar missing for some users",
    "Release candidate looks different from design",
    "Translation broke a label on the cart",
    "A/B test variant shows the wrong badge",
    "Nightly visual test flagged the home page",
    "Crash report points at the order summary",
  ],
  wires: [
    "Wire the payment API to the new checkout",
    "Connect the signup form to the auth service",
    "Route webhooks to the notification queue",
    "Hook the search box up to the new index",
    "Link the mobile app to the feature flags",
    "Pipe analytics events to the warehouse",
    "Connect the upload button to storage",
    "Move the email job onto the new worker",
    "Point the dashboard at the read replica",
    "Join the chat widget to the support inbox",
  ],
  ship: [
    "Cut the release for version 4.2",
    "Roll out the new onboarding to everyone",
    "Hotfix the login bug to production",
    "Ship the pricing page before the launch",
    "Deploy the database migration tonight",
    "Release the Android build to the store",
    "Turn on the feature flag for all users",
    "Push the security patch to every region",
    "Promote staging to production",
    "Ship the holiday banner on time",
  ],
  inbox: [
    "Triage this week's bug reports",
    "Sort the support queue before standup",
    "Answer the partner team's questions",
    "Clear the review requests waiting on you",
    "Go through the on-call handoff notes",
    "Reply to the design feedback thread",
    "Sort incoming feature requests",
    "Clean up the alerts channel",
    "Work through the security questionnaire",
    "Catch up on the incident follow-ups",
  ],
  oneonone: [
    "One-on-one with a new hire",
    "Check in with someone who seems tired",
    "Career talk with your strongest engineer",
    "Follow up on last week's hard feedback",
    "Coffee chat with a teammate thinking of leaving",
    "Weekly one-on-one with the tech lead",
    "Talk through a conflict between two teammates",
    "Growth plan for a junior engineer",
    "Welcome back chat after parental leave",
    "Listen to concerns about the reorg",
  ],
  sprint: [
    "Plan the next sprint",
    "Re-plan after the outage ate two days",
    "Fit the launch work into this sprint",
    "Balance bugs and features for the sprint",
    "Plan around two people on holiday",
    "Squeeze in the security fixes",
    "Rebalance the sprint after a scope change",
    "Plan the hardening sprint before release",
    "Size the backlog for next sprint",
    "Plan the sprint with the new teammate",
  ],
  roadmap: [
    "Draft next quarter's roadmap",
    "Choose what to cut from the launch",
    "Rank the requests from sales",
    "Plan the year with product leads",
    "Decide on the platform rewrite",
    "Order the migration projects",
    "Pick the team's bets for next half",
    "Review the roadmap after the reorg",
    "Balance tech debt against new features",
    "Prepare the roadmap for the board meeting",
  ],
};

export const URGENT_TITLES: readonly string[] = [
  "Production is down",
  "Checkout errors are spiking",
  "A big customer can't log in",
  "The CEO found a bug in the demo",
  "Payments are failing in one region",
  "The app store rejected the build",
];
